[cerebrium.deployment]
name = "ml-classifier"
python_version = "3.12"
docker_base_image_url = "debian:bookworm-slim"
disable_auth = false
include = ['./*', 'app.py', 'cerebrium.toml']
exclude = ['.*']

[cerebrium.hardware]
cpu = 2.0
memory = 12.0
compute = "CPU"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 1
response_grace_period = 900
scaling_metric = "concurrency_utilization"
scaling_target = 100
scaling_buffer = 0
roll_out_duration_seconds = 0

